### ISSUE TITLE
Virtual Product cause 500 Internal Server Error in checkout

### ISSUE THREAD

**Issue by Fredrik-H-Laastad** [DIBS-Payment-Services/magento2-dibs-flexwin#34]
Hi Maksim, 

Please set the  full issue description from the merchant below: 

I have the module configured in Magento but whenever we clicked the button that takes us to DIBS we get a spinning icon.

In the background we were getting a 500 internal server error when it calls the following.

• Request URL: http://alfasoft-dev.positive-dedicated.net/dibsflexwin/index/request 
• Request Method: POST 
• Status Code: 500 Internal Server Error

On the server we got the following error.

PHP Fatal error: Uncaught Error: Call to a member function getFirstname() on null in /home/mark/public_html/vendor/dibs/module-payment-flexwin/Model/Method.php:153\nStack trace:\n#0 /home/mark/public_html/vendor/dibs/module-payment-flexwin/Controller/Index/Request.php(26): Dibs\\Flexwin\\Model\\Method->collectRequestParams()\n#1 /home/mark/public_html/generated/code/Dibs/Flexwin/Controller/Index/Request/Interceptor.php(24): Dibs\\Flexwin\\Controller\\Index\\Request->execute()\n#2 /home/mark/public_html/vendor/magento/framework/App/Action/Action.php(107): Dibs\\Flexwin\\Controller\\Index\\Request\\Interceptor->execute()\n#3 /home/mark/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\\Framework\\App\\Action\\Action->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#4 /home/mark/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Dibs\\Flexwin\\Controller\\Index\\Request\\Interceptor->___callParent('dispatch', Array)\n#5 /home/mark/public_html/vendor/magento/framework/Interception/Interceptor.php(153): in /home/mark/public_html/vendor/dibs/module-payment-flexwin/Model/Method.php on line 153, referer: http://alfasoft-dev.positive-dedicated.net/checkout/ <http://alfasoft-dev.positive-dedicated.net/checkout/>

Now the problem we have is that Magento by default does not present a shipping address for a virtual product with no weight.

I have changed the code so that if the shippingAddress object is null it just uses the values from the billingAddress instead but thought that you should know in case you have any other thoughts about this and if this is a bad idea and will have an impact elsewhere in the module.

**Comment by maxwhite** [comment]
HI, thanks for your report, we'll fix it asap.
